FROM python:3.7
MAINTAINER Eduard Asriyan <ed-asriyan@protonmail.com>

WORKDIR /application

ADD requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && pip install psycopg2-binary==2.8.2 SQLAlchemy==1.3.3

ADD . .
ADD sign_unsigned_data.py .

CMD while true; do \
  python sign_unsigned_data.py --db-uri $DB_URI --device /dev/xbee; \
  sleep 10; \
  done;
